<#
.SYNOPSIS
    Make sure a .env exists with the three Kibana encryption keys.

.DESCRIPTION
    docker-compose.yml requires SIEM_ENCRYPTION_KEY, SIEM_ESO_ENCRYPTION_KEY and
    SIEM_REPORTING_ENCRYPTION_KEY, and deliberately has no fallback values: the
    fixed strings that used to be committed were readable by anyone, which meant
    they protected nothing (security audit H-3).

    This generates them once, from the system CSPRNG, into .env - which is
    git-ignored - so `docker compose up` works on a fresh clone with no manual
    step and the SOC Triage Board keeps working across restarts.

    Existing values are never overwritten. No key material is ever printed.
#>

function New-LabEnv {
    [CmdletBinding()]
    param(
        [string]$ProjectRoot = (Split-Path -Parent $PSScriptRoot)
    )

    $envPath = Join-Path $ProjectRoot ".env"

    $existing = @{}
    if (Test-Path $envPath) {
        foreach ($line in Get-Content $envPath) {
            if ($line -match '^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$') {
                $existing[$Matches[1]] = $Matches[2]
            }
        }
    }

    $required = @(
        "SIEM_ENCRYPTION_KEY",
        "SIEM_ESO_ENCRYPTION_KEY",
        "SIEM_REPORTING_ENCRYPTION_KEY"
    )
    $missing = @($required | Where-Object { -not $existing.ContainsKey($_) -or -not $existing[$_] })

    if ($missing.Count -eq 0) {
        return $false
    }

    # 32 random bytes -> 43 base64url characters, comfortably over the 32
    # characters Kibana wants. Generated locally and never transmitted.
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        $lines = @()
        if (-not (Test-Path $envPath)) {
            $lines += "# Generated by scripts/ensure_lab_env.ps1 on first run."
            $lines += "# Git-ignored. Holds this machine's Kibana encryption keys."
            $lines += "# Delete it to rotate; rotating invalidates existing saved objects,"
            $lines += "# so re-import the dashboard afterwards:"
            $lines += "#   python -m src.main import-dashboard"
            $lines += ""
        }
        foreach ($name in $missing) {
            $bytes = New-Object byte[] 32
            $rng.GetBytes($bytes)
            $value = [Convert]::ToBase64String($bytes).TrimEnd("=").Replace("+", "-").Replace("/", "_")
            $lines += "$name=$value"
        }
        Add-Content -Path $envPath -Value $lines
    }
    finally {
        $rng.Dispose()
    }

    # Reports only that it happened. The values stay on disk.
    Write-Host "  Created .env with $($missing.Count) generated encryption key(s)." -ForegroundColor DarkGray
    return $true
}
